.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. 5gl_qt test_5gl_qt
clean: FORCE
	$(MAKE) -C .. 5gl_qt_clean test_5gl_qt_clean
check: FORCE
	$(MAKE) -C .. test_5gl_qt_check
5gl-qt 5gl-qt.exe: FORCE
	 $(MAKE) -C .. 5gl_qt
